### ISSUE TITLE
USER - User APP ToDo

### ISSUE THREAD

**Issue by ErikPereira** [ErikPereira/PillHelper-APP#6]
TODO:

###  Description

5.  [x] Show Supervisors  
6.  [x] Delete Supervisors  
7.  [x] Fix bug Supervisors
6.  [x] Register Supervisors  

Required Merge Request

2.  [x] Show the Clinical Data information
3.  [x] Edit the Clinical Data information
5.  [x] Delete  Clinical Data
1.  [x] Add Clinical Data information

### Commit

1.  d0f62f121400e417275a5a54d3fd85bc7995b912 and 785570460edd7d88668b478d8aab6a594792dfa
2. 785570460edd7d88668b478d8aab6a594792dfa
3. 785570460edd7d88668b478d8aab6a594792dfa
4. 44a1005a88202bc43075fa6c13262173cf837975

Merge Request Done: USER-03_06: ToDo Supervisor in User Done #9

5. 1909d862faff28c23f8d6c0641efb8fd929e6a7d
6. 1909d862faff28c23f8d6c0641efb8fd929e6a7d
7. 1909d862faff28c23f8d6c0641efb8fd929e6a7d

Final Merge Requeste: USER-09_06: display clinical data DONE #10
