### ISSUE TITLE
SUP - Supervisor APP ToDo

### ISSUE THREAD

**Issue by ErikPereira** [ErikPereira/PillHelper-APP#7]
TODO:

###  Description

1.  [x] Create registration
2.  [x] Login
3.  [x] Delete users
4.  [x] Update Users
5.  [x] Register users
6.  [x] View user information
7.  [x] Fix bug retrun to FragmentsActivity (AllMedicinesActivity and RegisterBoxActivity)
8.  [x] Fix Bug show user 
9.  [x] Fix Bug show user medicines
10.  [x] Release supervisor access with permission only

### Commit

1.  77ec44471fb4ebb986af147aea37fa8c2090fda3
2.  77ec44471fb4ebb986af147aea37fa8c2090fda3
3.  bdc3cb14344dab814a7298c8712b88fdf7123b47
4.  bdc3cb14344dab814a7298c8712b88fdf7123b47
5.  89c26d5497aa6ec92693aaffb8f3cefcb57c479e and b8a13ebca461543861ef1d860c06bd1ec5bd759f
6.  e18000b90d9d46074e16f2feb0cc305d83393724
7.  1004bc816495c898fc1fad662d94c326ad8335bb
8.  fe76b71fab7ccd42202b7d3e1b3aa3c1b754ecc3
9.  bf61610449a631652ee20c0a42948308ffe28f0b
10. 77312d0a3e89f1e8144c831b3dcdfdd0701efb34
